routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// TODO: Remove when over with debugging routes
use App\Company;
use App\User;
use App\Event;
use App\Minisite;

Auth::routes();

Route::get('/filemanager/dialog.php', function(){
  ob_start();
  require(public_path(). '/filemanager/dialog.php');
  return ob_get_clean();
});

// Locales
//Route::post('lang', 'HomeController@changeLocal')->name('locale');
Route::get('language/{lang}', function($lang){
  Session::put('locale', $lang);
  return back();
})->name('langroute');

// Minisite V2 URL
Route::get('/s/{slug}-{minisiteId}/{page_slug}-{page}/{hash}/{lang?}', 'PageController@redirectNewUrl')
  ->where('page_slug', '[a-z0-9-]+')
  ->where('slug', '[a-z0-9-]+')
  ->name('minisite_page_show');
Route::get('/s/{slug}-{minisiteId}/{hash}/{lang?}', 'MinisiteController@redirectNewUrl')
  ->where('slug', '[a-z0-9-]+')
  ->name('minisite_show');

// subdomain routing
Route::domain('{domain}.'.config('app.url'))->group(function(){
  Route::get('/{page_slug}-{page}/{hash?}/{lang?}', 'PageController@show')
    ->where('page_slug', '[a-z0-9-]+')
    ->where('slug', '[a-z0-9-]+')
    ->where('lang', 'en|fr|de')
    ->name('minisite_page_subdomain_show');

  Route::get('/{hash?}/{lang?}', 'MinisiteController@show')
    ->where('slug', '[a-z0-9-]+')
    ->where('lang', 'en|fr|de')
    ->name('minisite_subdomain_show');

});

Route::get('/', 'HomeController@index')->name('home'); // TODO: Dashboard

Route::group(['namespace' => 'Admin', 'middleware' => ['auth', 'auth.admin']], function () {

  Route::get('changelog', 'AdminDashboardController@changelog')->name('admin.dashboard.changelog');

  Route::get('companies/{id}/_lock', 'CompaniesController@lock')->name('companies._lock');
  Route::get('companies/{id}/_unlock', 'CompaniesController@unlock')->name('companies._unlock');
  Route::resource('companies', 'CompaniesController');
  Route::resource('categories', 'CategoriesController');
  Route::resource('admins', 'UserController', ['except' => ['show']]);

  Route::get('admins/{user_id}/edit_permissions', 'UserController@editPermissions')->name('admin_edit_permissions');
  Route::post('admins/{user_id}/edit_permissions', 'UserController@updatePermissions')->name('admin_update_permissions');
});

// Auth based on company in URL
Route::group(['middleware' => ['auth', 'auth.owner.company:redirect']], function () {

  // Users
  Route::resource('companies.users', 'CompanyUserController', ['only' => [
      'index',
      'create',
      'store'
  ]]);

  Route::group(['middleware' => ['auth.owner.user:redirect']], function () {
    Route::resource('companies.users', 'CompanyUserController', ['except' => [
      'show',
      'index',
      'create',
      'store'
    ]]);

    Route::get('companies/{company}/users/{user_id}/edit_permissions', 'CompanyUserController@editPermissions')->name('edit_permissions');
    Route::post('companies/{company}/users/{user_id}/edit_permissions', 'CompanyUserController@updatePermissions')->name('update_permissions');
  });

  // Categories
  Route::resource('companies.categories', 'CompanyCategoryController', ['only' => [
    'index',
    'create',
    'store'
  ]]);

  Route::resource('companies.categories', 'CompanyCategoryController', ['except' => [
    'show',
    'index',
    'create',
    'store'
  ]])->middleware('auth.owner.category:redirect');

  // Events
  Route::get('/companies/{company}/events/statistics', 'EventStatisticsController@index')->name('companies.events.statistics.index');
  Route::get('/companies/{company}/events/statistics/export', 'EventStatisticsController@export')->name('companies.events.statistics.export');
  Route::get('/companies/{company}/events/past', 'CompanyEventController@past')->name('past_events');

  Route::resource('companies.events', 'CompanyEventController')->only(['index', 'create', 'store']);
  Route::group(['middleware' => ['event.active', 'auth.owner.event:redirect']], function () {
    Route::get('/companies/{company}/events/{event}/duplicate', 'CompanyEventController@duplicate')->name('companies.events.duplicate');
    Route::resource('companies.events', 'CompanyEventController')->except(['index', 'create', 'store']);
  });

  // Company SMTP configuration
  Route::get('/companies/{company}/config/edit', 'CompanySmtpController@edit')->name('companies.config');
  Route::patch('/companies/{company}/config/edit', 'CompanySmtpController@update')->name('companies.config.update');
});


// Auth based on event in URL
Route::group(['middleware' => ['auth', 'auth.owner.event:redirect', 'event.active']], function () {
  
  Route::post(
    'events/{event}/update_sessions_controls',
    'CompanyEventController@updateSessionsControls'
  )->name('events.update_sessions_controls');

  Route::post(
    'events/{event}/update_mandatory_category_session_control',
    'CompanyEventController@updateMandatoryCategorySessionControl'
  )->name('events.update_mandatory_category_session_control');
  
  // Emails
  Route::get('events/{event}/emails/createInvit', 'EmailsController@createInvit')->name('events.emails.createInvit');
  Route::get('events/{event}/emails/createOther', 'EmailsController@createOther')->name('events.emails.createOther');

  Route::resource('events.emails', 'EmailsController', ['only' => ['index']]);

  Route::group(['middleware' => ['auth.owner.email:redirect']], function () {
    Route::post('events/{event}/emails/{email}/duplicate', 'EmailsController@duplicate')
      ->name('events.email.duplicate');
    Route::get('events/{event}/emails/{email}/render/{display?}', 'EmailsController@render')
      ->where('display', 'mobile|desktop')
      ->name('events.emails.render');
    Route::get('events/{event}/emails/{email}/{lang?}/render/{display?}', 'EmailsController@render')
      ->where('display', 'mobile|desktop')
      ->name('events.emails.render.lang');
    Route::get('events/{event}/emails/{email}/render_template', 'EmailsController@renderTemplate')
      ->name('events.emails.render_template');
    Route::get('events/{event}/emails/{email}/{lang?}/render_template', 'EmailsController@renderTemplate')
      ->name('events.emails.render_template.lang');
  
    Route::get('events/{event}/emails/{email}/send', 'EmailsController@send')
      ->name('events.emails.send');

    Route::resource('events.emails', 'EmailsController', ['except' => ['show', 'create', 'edit', 'index', 'store']]);

    Route::get('events/{event}/emails/{email}/edit', 'EmailsController@edit')
      ->name('events.emails.edit');
    Route::get('events/{event}/emails/{email}/{lang?}/edit', 'EmailsController@edit')
      ->name('events.emails.edit.lang');
  });

  // Guests
  Route::post('events/{event}/guests/import', 'GuestsController@import')->name('events.guests.import');
  Route::get('events/{event}/guests/export', 'GuestsController@export')->name('events.guests.export');
  Route::get('events/{event}/guests/duplicates', 'GuestsController@duplicates')->name('events.guests.duplicates');
  Route::post('events/{event}/guests/validate_emails', 'GuestsController@validateEmails')->name('events.guests.validate_emails');

  Route::resource('events.guests', 'GuestsController', ['only' => ['create', 'store', 'index']]);
  Route::resource('events.guests', 'GuestsController', ['except' => [
    'show',
    'create',
    'store',
    'index'
  ]])->middleware('auth.owner.guest:redirect');

  // Checkin confirm
  // Compatibility redirection routes, will be removed
  // Can be safely removed after 10.08.2019. Except for event id 466 (Sponsorize tests).
  Route::get('events/{event}/guests/checkin/{hash_control}', function ($event, $hash_control) {
    return redirect()->route('guests.checkin', ['hash' => $hash_control]);
  });

  Route::get('events/{event}/checkin', 'CheckinController@index')->name('events.checkin.index');
  
  // Companions
  Route::get('events/{event}/guests/companions/export', 'GuestsController@exportCompanions')->name('events.guests.companions.export');
  Route::resource('events.companions', 'CompanionController', ['only' => [
    'edit',
    'update'
  ]])->middleware('auth.owner.companion:redirect');

  // Minisite
  Route::resource('events.minisites', 'MinisiteController', ['only' => ['index', 'create', 'store']]);
  Route::resource('events.minisites', 'MinisiteController', ['except' => [
    'destroy',
    'index',
    'create',
    'store'
  ]])->middleware('auth.owner.minisite:redirect');

  // Pages
  Route::get('events/{event}/minisites/{minisite}/pages/{lang?}/create', 'PageController@create')->name('page_create');
  Route::resource('events.minisites.pages', 'PageController', [ 'only' => ['store'] ]);
  Route::group(['middleware' => ['auth.owner.page:redirect']], function () {
    Route::get('events/{event}/minisites/{minisite}/pages/{page}/{lang?}/edit/{getlang?}', 'PageController@edit')->name('page_edit');
    Route::patch('events/{event}/minisites/{minisite}/pages/{page}/{lang?}/update', 'PageController@update')->name('page_update');
    Route::resource('events.minisites.pages', 'PageController', [ 'except' => ['update', 'store'] ]);
  });

  // SubscribeForms
  Route::get('events/{event}/subscribeForm/edit', 'SubscribeFormController@edit')->name('events.subscribeForm.edit');

  // SurveyForms
  Route::get('events/{event}/surveyForm/results', 'SurveyFormController@results')->name('events.surveyForm.results');
  Route::get('events/{event}/surveyForm/edit', 'SurveyFormController@edit')->name('events.surveyForm.edit');

  // Sessions
  Route::resource('events.sessions', 'SessionController', [ 'only' => ['create', 'store', 'index'] ]);

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Attributes
 * - id   : int(10) unsigned
 * - companyName : varchar(255)
 * - firstname : varchar(255)
 * - lastname : varchar(255)
 * - phone : varchar(255)
 * - email : varchar(255)
 * - created_at : Date
 * - updated_at : Date
 * - lock : boolean
 * - smtp_host : varchar(255)
 * - smtp_port : int(11)
 * - smtp_from_mail_address : varchar(255)
 * - smtp_from_name : varchar(255)
 * - smtp_encryption : varchar(255)
 * - smtp_username : varchar(255)
 * - smtp_password : varchar(255)
 * - active : boolean
 */
class Company extends Model
{
  protected $table = 'companies';
  protected $primaryKey = 'id';

  protected $fillable = ['companyName', 'firstname', 'lastname', 
    'phone', 'email', 'smtp_host', 'smtp_port', 'smtp_from_mail_address', 
    'smtp_from_name', 'smtp_encryption', 'smtp_encryption', 'smtp_password'];

  protected $hidden = ['users', 'categories', 'events', 'templates'];

  public function hasCompleteSMTPConfig()
  {
    return $this->smtp_host != null && $this->smtp_port != null &&
      $this->smtp_from_mail_address != null && $this->smtp_from_name != null &&
      $this->smtp_password != null;
  }

  // Relations

  public function users()
  {
    return $this->hasMany('App\User');
  }

  public function categories()
  {
    return $this->hasMany('App\Category');
  }

  public function events()
  {
    return $this->hasMany('App\Event');
  }

  public function templates()
  {
    return $this->hasMany('App\Template');
  }

  public function MinisiteTemplates(){
    return $this->templates()->where("template_type", "MINISITE")->get();
  }

  public function EmailTemplates(){
    return $this->templates()->where("template_type", "EMAIL")->get();
  }
}

app/Http/Controllers/Admin/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Company;
use Illuminate\Http\Request;
use Session;
use File;

use App\Http\Requests\CompanyCreateRequest;
use App\Http\Requests\CompanyUpdateRequest;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $companies = Company::where('active', true)
            ->orderBy('companyName', 'asc')
            ->paginate(25);
        return view('admin.companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admin.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CompanyCreateRequest $request)
    {
        $requestData = $request->all();

        $company_id = Company::create($requestData)->id;

        // Create the subfolder of images for minisite
        $path = public_path().'/source/subfolder-' . $company_id;
        File::makeDirectory($path, $mode = 0777, true, true);

        Session::flash('flash_message', 'Company added!');

        return redirect('companies');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $company = Company::findOrFail($id);

        return view('admin.companies.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $company = Company::findOrFail($id);

        return view('admin.companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update($id, CompanyUpdateRequest $request)
    {
        $requestData = $request->all();

        $company = Company::findOrFail($id);
        $company->update($requestData);

        Session::flash('flash_message', 'Company updated!');

        return redirect('companies');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $company = Company::where('id', $id)->first();
        $company->active = false;
        $company->save();

        Session::flash('flash_message', 'Company successfully deleted!');

        return redirect('companies');
    }


    public function lock($id)
    {
        $this->setLockCompany($id, true);
        Session::flash('flash_message', 'Company locked!');
        return redirect('companies');
    }

    public function unlock($id)
    {
        $this->setLockCompany($id, false);
        Session::flash('flash_message', 'Company unlocked!');
        return redirect('companies');
    }

    private function setLockCompany($companyId, $lockState)
    {
        $company = Company::findOrFail($companyId);
        $company->lock = $lockState;
        return $company->save();
    }
}

resources/views/admin/companies/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-full">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9 page-content">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ ucfirst(trans_choice('models.company.company', 1)) }}</div>
                    <div class="panel-body">
                        <a href="{{ route('companies.index') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> {{ ucfirst(__('interface.back')) }}</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        {!! Form::open(['url' => '/companies', 'class' => 'form-horizontal', 'files' => true]) !!}

                        @include ('admin.companies.form')

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/companies/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-full">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9 page-content">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ ucfirst(trans_choice('models.company.company', 1)) }} #{{ $company->id }}</div>
                    <div class="panel-body">
                        <a href="{{ route('companies.index') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> {{ ucfirst(__('interface.back')) }} </button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        {!! Form::model($company, [
                            'method' => 'PATCH',
                            'url' => ['/companies', $company->id],
                            'class' => 'form-horizontal',
                            'files' => true
                        ]) !!}

                        @include ('admin.companies.form', ['submitButtonText' => ucfirst(__('interface.update'))])

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/companies/form.blade.php
<div class="form-group {{ $errors->has('companyName') ? 'has-error' : ''}}">
    {!! Form::label('companyName', ucfirst(__('validation.attributes.companyName')), ['class' => 'col-md-4 control-label']) !!}
    <div class="col-md-6">
        {!! Form::text('companyName', null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! $errors->first('companyName', '<p class="help-block">:message</p>') !!}
    </div>
</div><div class="form-group {{ $errors->has('firstname') ? 'has-error' : ''}}">
    {!! Form::label('firstname', ucfirst(__('validation.attributes.first_name')), ['class' => 'col-md-4 control-label']) !!}
    <div class="col-md-6">
        {!! Form::text('firstname', null, ['class' => 'form-control']) !!}
        {!! $errors->first('firstname', '<p class="help-block">:message</p>') !!}
    </div>
</div><div class="form-group {{ $errors->has('lastname') ? 'has-error' : ''}}">
    {!! Form::label('lastname', ucfirst(__('validation.attributes.last_name')), ['class' => 'col-md-4 control-label']) !!}
    <div class="col-md-6">
        {!! Form::text('lastname', null, ['class' => 'form-control']) !!}
        {!! $errors->first('lastname', '<p class="help-block">:message</p>') !!}
    </div>
</div><div class="form-group {{ $errors->has('phone') ? 'has-error' : ''}}">
    {!! Form::label('phone', ucfirst(__('validation.attributes.phone')), ['class' => 'col-md-4 control-label']) !!}
    <div class="col-md-6">
        {!! Form::text('phone', null, ['class' => 'form-control']) !!}
        {!! $errors->first('phone', '<p class="help-block">:message</p>') !!}
    </div>
</div><div class="form-group {{ $errors->has('email') ? 'has-error' : ''}}">
    {!! Form::label('email', ucfirst(__('validation.attributes.email')), ['class' => 'col-md-4 control-label']) !!}
    <div class="col-md-6">
        {!! Form::text('email', null, ['class' => 'form-control']) !!}
        {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-4 col-md-4">
        {!! Form::submit(isset($submitButtonText) ? $submitButtonText : ucfirst(__('interface.create')), ['class' => 'btn btn-primary']) !!}
    </div>
</div>

resources/views/admin/companies/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-full">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9 page-content">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {{ ucfirst(trans_choice('models.company.company', 2)) }}
                        <div class="pull-right">
                            <a href="{{ route('companies.create') }}" class="btn btn-success btn-sm" title="{{ ucfirst(__('interface.add')) }}">
                                <i class="fa fa-plus" aria-hidden="true"></i> {{ ucfirst(__('interface.add')) }}
                            </a>
                        </div>
                    </div>
                    <div class="panel-body">
                        
                        <!--<div>
                            {!! Form::open(['method' => 'GET', 'url' => '/companies', 'class' => '', 'role' => 'search'])  !!}
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="{{ ucfirst(__('interface.search')) }}...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            {!! Form::close() !!}
                        </div>

                        <br/>-->

                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th>#</th><th>{{ ucfirst(__('validation.attributes.companyName')) }}</th><th> {{ ucfirst(__('validation.attributes.first_name')) }} </th><th>{{ ucfirst(__('validation.attributes.last_name')) }}</th><th>&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($companies as $item)
                                    <tr>
                                        <td>{{ $item->id }}</td>
                                        <td>{{ $item->companyName }}</td>
                                        <td>{{ $item->firstname }}</td>
                                        <td>{{ $item->lastname }}</td>
                                        <td class="text-right">
                                            <a href="{{ route('companies.show', [$item]) }}" class="btn btn-info btn-xs" title="View Company">
                                                <i class="fa fa-eye" aria-hidden="true"></i> {{ ucfirst(__('interface.show')) }}
                                            </a>
                                            <a href="{{ route('companies.edit', [$item]) }}" class="btn btn-primary btn-xs" title="Edit Company">
                                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{ ucfirst(__('interface.edit')) }}
                                            </a>

                                            {!! Form::open([
                                                'method'=>'DELETE',
                                                'url' => ['/companies', $item->id],
                                                'style' => 'display:inline'
                                            ]) !!}
                                                {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> ' . ucfirst(__('interface.delete')), array(
                                                        'type' => 'submit',
                                                        'class' => 'btn btn-danger btn-xs',
                                                        'title' => 'Delete Company',

                                                        'onclick'=>"return confirm('" . ucfirst(__('interface.confirm_delete_object', ['name' => $item->companyName])) . "')"
                                                )) !!}
                                            {!! Form::close() !!}

                                            <div class="btn-ctrl-div">
                                                @if ($item->lock)
                                                    <a href="{{ route('companies._unlock', [$item]) }}" 
                                                        class="btn btn-success btn-xs"
                                                        title="Unlock Company"
                                                        onclick='return confirm("{{ ucfirst(__('interface.companies_page.confirm_unlock', ['name' => $item->companyName])) }}")'>
                                                        <i class="fa fa-lock" aria-hidden="true"></i> {{ ucfirst(__('interface.unlock')) }}
                                                    </a>
                                                @else
                                                    <a href="{{ route('companies._lock', [$item]) }}"
                                                        class="btn btn-danger btn-xs"
                                                        title="Lock Company"
                                                        onclick='return confirm("{{ ucfirst(__('interface.companies_page.confirm_lock', ['name' => $item->companyName])) }}")'
                                                        >
                                                        <i class="fa fa-unlock" aria-hidden="true"></i> {{ ucfirst(__('interface.lock')) }}
                                                    </a>
                                                @endif

                                                <a href="{{ route('companies.users.index', [$item]) }}" class="btn btn-success btn-xs" title="Show users">
                                                   <i class="fa fa-folder-open-o" aria-hidden="true"></i> {{ ucfirst(__('interface.open')) }}
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! $companies->appends(['search' => Request::get('search')])->render() !!} </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/companies/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-full">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9 page-content">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ ucfirst(trans_choice('models.company.company', 1)) }} #{{ $company->id }}</div>
                    <div class="panel-body">

                        @if ($company->lock)
                            <a href="{{ route('companies._unlock', [$company]) }}" title="Unlock Company"><button class="btn btn-success btn-xs"><i class="fa fa-lock" aria-hidden="true"></i> {{ ucfirst(__('interface.unlock')) }}</button></a>
                        @else
                            <a href="{{ route('companies._lock', [$company]) }}" title="Lock Company"><button class="btn btn-danger btn-xs"><i class="fa fa-unlock" aria-hidden="true"></i> {{ ucfirst(__('interface.lock')) }}</button></a>
                        @endif
                        <a href="{{ route('companies.edit', [$company]) }}" title="Edit Company"><button class="btn btn-primary btn-xs"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{ ucfirst(__('interface.edit')) }}</button></a>
                        
                        {!! Form::open([
                            'method'=>'DELETE',
                            'url' => ['/companies', $company->id],
                            'style' => 'display:inline'
                        ]) !!}
                            {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> ' . ucfirst(__('interface.delete')), array(
                                    'type' => 'submit',
                                    'class' => 'btn btn-danger btn-xs',
                                    'title' => 'Delete Company',
                                    'onclick'=>'return confirm("' . ucfirst(__('interface.confirm_delete')) . '")'
                            )) !!}
                        {!! Form::close() !!}

                        <a href="{{ route('companies.users.index', [$company]) }}" title="Show users"><button class="btn btn-primary btn-xs"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{ ucfirst(__('interface.open')) }}</button></a>

                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <tbody>
                                    <tr>
                                        <th>#</th><td>{{ $company->id }}</td>
                                    </tr>
                                    <tr><th> {{ ucfirst(__('validation.attributes.companyName')) }} </th><td> {{ $company->companyName }} </td></tr>
                                    <tr><th> {{ ucfirst(__('validation.attributes.last_name')) }} </th><td> {{ $company->lastname }} </td></tr>
                                    <tr><th> {{ ucfirst(__('validation.attributes.first_name')) }} </th><td> {{ $company->firstname }} </td></tr>
                                    <tr><th> {{ ucfirst(__('validation.attributes.phone')) }} </th><td> {{ $company->phone }} </td></tr>
                                    <tr><th> {{ ucfirst(__('validation.attributes.email')) }} </th><td> {{ $company->email }} </td></tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection