routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// TODO: Remove when over with debugging routes
use App\Company;
use App\User;
use App\Event;
use App\Minisite;

Auth::routes();

Route::get('/filemanager/dialog.php', function(){
  ob_start();
  require(public_path(). '/filemanager/dialog.php');
  return ob_get_clean();
});

// Locales
//Route::post('lang', 'HomeController@changeLocal')->name('locale');
Route::get('language/{lang}', function($lang){
  Session::put('locale', $lang);
  return back();
})->name('langroute');

// Minisite V2 URL
Route::get('/s/{slug}-{minisiteId}/{page_slug}-{page}/{hash}/{lang?}', 'PageController@redirectNewUrl')
  ->where('page_slug', '[a-z0-9-]+')
  ->where('slug', '[a-z0-9-]+')
  ->name('minisite_page_show');
Route::get('/s/{slug}-{minisiteId}/{hash}/{lang?}', 'MinisiteController@redirectNewUrl')
  ->where('slug', '[a-z0-9-]+')
  ->name('minisite_show');

// subdomain routing
Route::domain('{domain}.'.config('app.url'))->group(function(){
  Route::get('/{page_slug}-{page}/{hash?}/{lang?}', 'PageController@show')
    ->where('page_slug', '[a-z0-9-]+')
    ->where('slug', '[a-z0-9-]+')
    ->where('lang', 'en|fr|de')
    ->name('minisite_page_subdomain_show');

  Route::get('/{hash?}/{lang?}', 'MinisiteController@show')
    ->where('slug', '[a-z0-9-]+')
    ->where('lang', 'en|fr|de')
    ->name('minisite_subdomain_show');

});

Route::get('/', 'HomeController@index')->name('home'); // TODO: Dashboard

Route::group(['namespace' => 'Admin', 'middleware' => ['auth', 'auth.admin']], function () {

  Route::get('changelog', 'AdminDashboardController@changelog')->name('admin.dashboard.changelog');

  Route::get('companies/{id}/_lock', 'CompaniesController@lock')->name('companies._lock');
  Route::get('companies/{id}/_unlock', 'CompaniesController@unlock')->name('companies._unlock');
  Route::resource('companies', 'CompaniesController');
  Route::resource('categories', 'CategoriesController');
  Route::resource('admins', 'UserController', ['except' => ['show']]);

  Route::get('admins/{user_id}/edit_permissions', 'UserController@editPermissions')->name('admin_edit_permissions');
  Route::post('admins/{user_id}/edit_permissions', 'UserController@updatePermissions')->name('admin_update_permissions');
});

// Auth based on company in URL
Route::group(['middleware' => ['auth', 'auth.owner.company:redirect']], function () {

  // Users
  Route::resource('companies.users', 'CompanyUserController', ['only' => [
      'index',
      'create',
      'store'
  ]]);

  Route::group(['middleware' => ['auth.owner.user:redirect']], function () {
    Route::resource('companies.users', 'CompanyUserController', ['except' => [
      'show',
      'index',
      'create',
      'store'
    ]]);

    Route::get('companies/{company}/users/{user_id}/edit_permissions', 'CompanyUserController@editPermissions')->name('edit_permissions');
    Route::post('companies/{company}/users/{user_id}/edit_permissions', 'CompanyUserController@updatePermissions')->name('update_permissions');
  });

  // Categories
  Route::resource('companies.categories', 'CompanyCategoryController', ['only' => [
    'index',
    'create',
    'store'
  ]]);

  Route::resource('companies.categories', 'CompanyCategoryController', ['except' => [
    'show',
    'index',
    'create',
    'store'
  ]])->middleware('auth.owner.category:redirect');

  // Events
  Route::get('/companies/{company}/events/statistics', 'EventStatisticsController@index')->name('companies.events.statistics.index');
  Route::get('/companies/{company}/events/statistics/export', 'EventStatisticsController@export')->name('companies.events.statistics.export');
  Route::get('/companies/{company}/events/past', 'CompanyEventController@past')->name('past_events');

  Route::resource('companies.events', 'CompanyEventController')->only(['index', 'create', 'store']);
  Route::group(['middleware' => ['event.active', 'auth.owner.event:redirect']], function () {
    Route::get('/companies/{company}/events/{event}/duplicate', 'CompanyEventController@duplicate')->name('companies.events.duplicate');
    Route::resource('companies.events', 'CompanyEventController')->except(['index', 'create', 'store']);
  });

  // Company SMTP configuration
  Route::get('/companies/{company}/config/edit', 'CompanySmtpController@edit')->name('companies.config');
  Route::patch('/companies/{company}/config/edit', 'CompanySmtpController@update')->name('companies.config.update');
});


// Auth based on event in URL
Route::group(['middleware' => ['auth', 'auth.owner.event:redirect', 'event.active']], function () {
  
  Route::post(
    'events/{event}/update_sessions_controls',
    'CompanyEventController@updateSessionsControls'
  )->name('events.update_sessions_controls');

  Route::post(
    'events/{event}/update_mandatory_category_session_control',
    'CompanyEventController@updateMandatoryCategorySessionControl'
  )->name('events.update_mandatory_category_session_control');
  
  // Emails
  Route::get('events/{event}/emails/createInvit', 'EmailsController@createInvit')->name('events.emails.createInvit');
  Route::get('events/{event}/emails/createOther', 'EmailsController@createOther')->name('events.emails.createOther');

  Route::resource('events.emails', 'EmailsController', ['only' => ['index']]);

  Route::group(['middleware' => ['auth.owner.email:redirect']], function () {
    Route::post('events/{event}/emails/{email}/duplicate', 'EmailsController@duplicate')
      ->name('events.email.duplicate');
    Route::get('events/{event}/emails/{email}/render/{display?}', 'EmailsController@render')
      ->where('display', 'mobile|desktop')
      ->name('events.emails.render');
    Route::get('events/{event}/emails/{email}/{lang?}/render/{display?}', 'EmailsController@render')
      ->where('display', 'mobile|desktop')
      ->name('events.emails.render.lang');
    Route::get('events/{event}/emails/{email}/render_template', 'EmailsController@renderTemplate')
      ->name('events.emails.render_template');
    Route::get('events/{event}/emails/{email}/{lang?}/render_template', 'EmailsController@renderTemplate')
      ->name('events.emails.render_template.lang');
  
    Route::get('events/{event}/emails/{email}/send', 'EmailsController@send')
      ->name('events.emails.send');

    Route::resource('events.emails', 'EmailsController', ['except' => ['show', 'create', 'edit', 'index', 'store']]);

    Route::get('events/{event}/emails/{email}/edit', 'EmailsController@edit')
      ->name('events.emails.edit');
    Route::get('events/{event}/emails/{email}/{lang?}/edit', 'EmailsController@edit')
      ->name('events.emails.edit.lang');
  });

  // Guests
  Route::post('events/{event}/guests/import', 'GuestsController@import')->name('events.guests.import');
  Route::get('events/{event}/guests/export', 'GuestsController@export')->name('events.guests.export');
  Route::get('events/{event}/guests/duplicates', 'GuestsController@duplicates')->name('events.guests.duplicates');
  Route::post('events/{event}/guests/validate_emails', 'GuestsController@validateEmails')->name('events.guests.validate_emails');

  Route::resource('events.guests', 'GuestsController', ['only' => ['create', 'store', 'index']]);
  Route::resource('events.guests', 'GuestsController', ['except' => [
    'show',
    'create',
    'store',
    'index'
  ]])->middleware('auth.owner.guest:redirect');

  // Checkin confirm
  // Compatibility redirection routes, will be removed
  // Can be safely removed after 10.08.2019. Except for event id 466 (Sponsorize tests).
  Route::get('events/{event}/guests/checkin/{hash_control}', function ($event, $hash_control) {
    return redirect()->route('guests.checkin', ['hash' => $hash_control]);
  });

  Route::get('events/{event}/checkin', 'CheckinController@index')->name('events.checkin.index');
  
  // Companions
  Route::get('events/{event}/guests/companions/export', 'GuestsController@exportCompanions')->name('events.guests.companions.export');
  Route::resource('events.companions', 'CompanionController', ['only' => [
    'edit',
    'update'
  ]])->middleware('auth.owner.companion:redirect');

  // Minisite
  Route::resource('events.minisites', 'MinisiteController', ['only' => ['index', 'create', 'store']]);
  Route::resource('events.minisites', 'MinisiteController', ['except' => [
    'destroy',
    'index',
    'create',
    'store'
  ]])->middleware('auth.owner.minisite:redirect');

  // Pages
  Route::get('events/{event}/minisites/{minisite}/pages/{lang?}/create', 'PageController@create')->name('page_create');
  Route::resource('events.minisites.pages', 'PageController', [ 'only' => ['store'] ]);
  Route::group(['middleware' => ['auth.owner.page:redirect']], function () {
    Route::get('events/{event}/minisites/{minisite}/pages/{page}/{lang?}/edit/{getlang?}', 'PageController@edit')->name('page_edit');
    Route::patch('events/{event}/minisites/{minisite}/pages/{page}/{lang?}/update', 'PageController@update')->name('page_update');
    Route::resource('events.minisites.pages', 'PageController', [ 'except' => ['update', 'store'] ]);
  });

  // SubscribeForms
  Route::get('events/{event}/subscribeForm/edit', 'SubscribeFormController@edit')->name('events.subscribeForm.edit');

  // SurveyForms
  Route::get('events/{event}/surveyForm/results', 'SurveyFormController@results')->name('events.surveyForm.results');
  Route::get('events/{event}/surveyForm/edit', 'SurveyFormController@edit')->name('events.surveyForm.edit');

  // Sessions
  Route::resource('events.sessions', 'SessionController', [ 'only' => ['create', 'store', 'index'] ]);

app/Http/Controllers/MinisiteController.php
<?php

namespace App\Http\Controllers;

use Image;
use App\Minisite;
use App\Page;
use App\Event;
use App\Guest;
use File;
use App\Companion;
use Illuminate\Http\Request;

use App\Http\Requests\MinisiteCreateRequest;
use App\Facades\MinisiteService;

use App\Utils\LocaleUtil;

class MinisiteController extends Controller
{
  public function index(Event $event)
  {
    // verify 
    $path = public_path('source/'.'subfolder-' . $event->company()->get()->first()->id, 0, '/');
    if(!File::exists($path)) {
      // mkdir($path, 0755, true);
      File::makeDirectory($path, $mode = 0755, true, true);
    }

    $this->authorize('index', Minisite::class);

    $event->load('company', 'company.templates');

    $company = $event->company;
    $minisite = Minisite::where('event_id', $event->id)->with('pages', 'pages.pageType')->get()->first();
    $accessHash = $event->getDemoHash();

    //change it to select the templates for minisites only
    //$company->load('templates');
    $templates = $company->templates;

    return view('minisite.index', compact(['company', 'event', 'minisite', 'accessHash', 'templates']));
  }

  public function create(Event $event)
  {
    $this->authorize('create', Minisite::class);

    $company = $event->company()->get();
    $minisite = Minisite::where('event_id', $event->id)->get()->first();

    # If a minisite already exists
    if ($minisite != null) {
      $edit_mode = true;
      return redirect()->route('events.minisites.edit', ['event' => $event->id, 'minisite' => $minisite->id, 'edit_mode' => $edit_mode]);
    }
    else {
      $edit_mode = false;
      return view('minisite.create', compact(['company', 'event', 'edit_mode']));
    }
  }

  public function store(MinisiteCreateRequest $request, Event $event)
  {
    $this->authorize('create', Minisite::class);
    $data = $request->all();

    $minisite = new Minisite($data);

    $minisite->event_id = $event->id;

    $bgImg = $request->file('site_background_image');
    $bottomImg = $request->file('bottom_image_path');
    $topImg = $request->file('site_top_image');
    
    if($bgImg != null){
      $name = time() . '.' . $bgImg->getClientOriginalExtension();
      MinisiteService::saveBackgroundImage($bgImg, $name);
      $minisite->site_background_image = '/uploads/images/bg_img/' . $name;
    }
    if($bottomImg != null){
      $name = time() . '.' . $bottomImg->getClientOriginalExtension();
      MinisiteService::saveBottomImage($bottomImg, $name);
      $minisite->bottom_image_path = '/uploads/images/bottom_img/' . $name;
    }
    if($topImg != null){
      $name = time() . '.' . $topImg->getClientOriginalExtension();
      MinisiteService::saveTopImage($topImg, $name);
      $minisite->site_top_image = '/uploads/images/top_img/' . $name;
    }

    $minisite->save();
    return redirect()->route('events.minisites.index', [$event]);
  }

  public function redirectNewUrl($slug, $minisiteId, $hash, $lang='fr')
  {
    $minisite = Minisite::findOrFail($minisiteId);
    return redirect()->route('minisite_subdomain_show', [
      'slug' => $minisite->slug,
      'hash' => $hash,
      'lang' => $lang
    ]);
  }

  /**
   * Show minisite
   * If minisite is public $hash may be null
   */
  public function show($slug, $hash=null, $lang=null)
  {
    $minisite = Minisite::where('slug', $slug)->with('event', 'pages')->firstOrFail();
    $pages = $minisite->pages()->orderBy('order_id', 'ASC')->get();
    $event = $minisite->event()->with('surveyForm')->first();

    $setLang = $event->getLangsAttribute()[0];

    // TODO: DRY this code with PageController@show
    if(in_array($hash, ['fr', 'de', 'en'])) { // avoid to have double $lang in URL
      $setLang = $hash;
      $hash = null;
    }

    if($pages->count() <= 0) {
      return view('minisite.under_construction');
    }

    //$demo = $event->isValidDemoHash($hash);  // Check hash if Private minisite
    $guest = Guest::with('event', 'event.surveyForm')->where('accessHash', $hash)->active()->first();
    $companion = Companion::where('access_hash', $hash)->first();

    $page = $minisite->pages()->accessibleByGuest()->orderBy('order_id', 'ASC')->first();
    if (isset($companion)) {
      $page = $minisite->pages()->accessibleByCompanion()->orderBy('order_id', 'ASC')->first();
    }

    if (!$event->active || !isset($page)) {
      abort(404, 'Page not found');
    }

    if (!MinisiteService::verifyPageAccess($event, $page, $guest, $companion, $hash)) {
      return view('subscribeForms.notallowed');
    }

    $demo = $event->isValidDemoHash($hash);

    // Defining minisite lang
    if(is_null($lang) && isset($guest) && !is_null($guest->language) && in_array($guest->language, $event->getLangsAttribute())){
      $lang = $guest->language;
    }else if(is_null($lang)){
      $lang = $setLang;
    }

    LocaleUtil::changeLocal($lang);

    // Survey form
    $surveyForm = $event->surveyForm()->first();

    // Subscribe form
    $subscribeForm = $event->subscribeForm()->first();

    $minAttributes = Guest::getMinAttributes();

    return view('minisite.show', compact([
      'minisite', 
      'pages', 
      'page', 
      'event', 
      'surveyForm', 
      'subscribeForm', 
      'guest', // can be null !
      'companion', // can be null ! 
      'hash', 
      'lang',
      'minAttributes',
      'demo'
    ]));
  }

  public function edit(Event $event, Minisite $minisite)
  {
    $this->authorize('edit', Minisite::class);

    $company = $event->company()->get();
    $edit_mode = true;
    return view('minisite.edit', compact(['company', 'event', 'minisite', 'edit_mode']));
  }

  public function update(MinisiteCreateRequest $request, Event $event, Minisite $minisite)
  {
    $this->authorize('edit', Minisite::class);
    $data = $request->except(['keep_bg_img_file', 'keep_bottom_img_file', 'keep_top_img_file']);

    // We do not keep the file, we have to delete it
    if(!$request->input("keep_bg_img_file") OR $request->input("keep_bg_img_file") != 1){
      if(file_exists(public_path($minisite->site_background_image))){
        unlink(public_path($minisite->site_background_image));
      }
      $minisite->site_background_image = null;
    }

    if(!$request->input("keep_bottom_img_file") OR $request->input("keep_bottom_img_file") != 1){
      if(file_exists(public_path($minisite->bottom_image_path))){
        unlink(public_path($minisite->bottom_image_path));
      }
      $minisite->bottom_image_path = null;
    }

    if(!$request->input("keep_top_img_file") OR $request->input("keep_top_img_file") != 1){
      if(file_exists(public_path($minisite->site_top_image))){
        unlink(public_path($minisite->site_top_image));
      }
      $minisite->site_top_image = null;
    }

    $minisite->update($data);

    $bgImg = $request->file('site_background_image');
    $bottomImg = $request->file('bottom_image_path');
    $topImg = $request->file('site_top_image');
    
    if($bgImg != null){
      $name = time() . '.' . $bgImg->getClientOriginalExtension();
      MinisiteService::saveBackgroundImage($bgImg, $name);
      $minisite->site_background_image = '/uploads/images/bg_img/' . $name;
    }
    if($bottomImg != null){
      $name = time() . '.' . $bottomImg->getClientOriginalExtension();
      MinisiteService::saveBottomImage($bottomImg, $name);
      $minisite->bottom_image_path = '/uploads/images/bottom_img/' . $name;
    }
    if($topImg != null){
      $name = time() . '.' . $topImg->getClientOriginalExtension();
      MinisiteService::saveTopImage($topImg, $name);
      $minisite->site_top_image = '/uploads/images/top_img/' . $name;
    }

    $minisite->save();

    return redirect()->route('events.minisites.index', [$event]);
  }
}

resources/views/minisite/_table_pages.blade.php
{{-- -------------------------------------
------- Minisite page list section -------
------------------------------------------
--
-- A list of pages available for this minisite
--}}

<h4>{{ ucfirst(trans_choice('models.pages.site_pages', 1)) }}</h4>
<p><small>{{ ucfirst(trans_choice('models.pages.under_list', 1)) }}</small></p>
@can('edit', App\Minisite::class)

    <div class="btn-group">
    <button type="button" class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-test="minisite-add-page-button">
        <i class="fa fa-plus fa-fw"></i> {{ ucfirst(trans_choice('interface.add', 1)) }} page <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        @forelse ($event->availableLanguages() as $e_lang)
            <li><a href="{{ route('page_create', ['event' =>$event, 'minisite' => $minisite, 'lang' => $e_lang]) }}" data-test="minisite-page-lang-choice-{{ $e_lang }}">{{ $e_lang }}</a></li>
            @empty
            {{ __('interface.minisites_page.no_language') }}
        @endforelse
    </ul>
    </div>

@endcan

{{-- Table of pages --}}

<table class="table table-hover table-bordered pages-table">
    @forelse ($minisite->pages->sortBy('order_id') as $page)
    <tr>
        <td>
        <div>
            <strong><span class="text-muted" style="color:#CCC;">#{{ $page->order_id }}</span>
            @forelse ($page->availableLanguages() as $p_lang)
                <a href="{{ route("minisite_page_subdomain_show", [$minisite->slug, $page->{'slug_' . $p_lang}, $page, $accessHash, $p_lang]) }}" target="_blank">
                {{ str_limit($page->{'name_' . $p_lang}, 15, '...') }}
                </a>
                <small class="text-muted">({{ $p_lang }})</small>&nbsp;
            @empty
                {{ __('interface.minisites_page.no_language') }}
            @endforelse
            </strong>


            {{-- Actions on pages --}}

            <div class="pull-right">
            <div class="row">
                <div class="col-md-12">
                @can('edit', App\Minisite::class)
                    <div class="btn-group">
                    <button type="button" class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-test="page-edit-properties-button-{{ $page->order_id }}">
                        {{ ucfirst(trans_choice('interface.edit_properties', 1)) }} <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">

                        @forelse ($event->availableLanguages() as $e_lang)
                        <li>
                        <a href="{{ route('page_edit', [$event, $minisite, $page, $e_lang]) }}" data-test="page-edit-button-{{ $e_lang }}-{{ $page->order_id }}">
                            @if ($page->{'content_' . $e_lang} == "" || is_null($page->{'content_' . $e_lang}))
                            <i class="text-warning fa fa-warning"></i>
                            @else
                            <i class="text-success fa fa-check"></i>
                            @endif

                        {{ $e_lang }}
                        </a>
                    </li>
                    @empty
                        {{ __('interface.minisites_page.no_language') }}
                    @endforelse
                    </ul>
                </div>
                @endcan
                @can('edit', App\Minisite::class)
                <form method="POST" style="display:inline;" action="{{ route('events.minisites.pages.destroy', ['event' => $event, 'minisite' => $minisite, 'page' => $page]) }}">
                    {{ method_field('DELETE') }}
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <button type="submit"
                        class="btn btn-xs btn-danger"
                        onclick="return confirm('{{ ucfirst(__('interface.confirm_delete_object', ['name' => $page->name])) }}')">
                        {{ ucfirst(trans_choice('interface.delete', 1)) }}
                    </button>
                </form>
                @endcan
            </div>
            </div>


            @can('edit', App\Minisite::class)
            <div class="row">
            <div class="col-md-12" style="padding-top: 5px;">
                <div class="pull-right">
                @if ($minisite->pages->count() > 1)
                    @if ($loop->first)
                        <form method="POST" style="display:inline;" action="{{ route('minisite.pages.page_down', ['minisite' => $minisite, 'page' => $page]) }}">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-xs"><i class="glyphicon glyphicon-chevron-down"></i></button>
                        </form>
                    @elseif ($loop->last)
                        <form method="POST" style="display:inline;" action="{{ route('minisite.pages.page_up', ['minisite' => $minisite, 'page' => $page]) }}">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-xs"><i class="glyphicon glyphicon-chevron-up"></i></button>
                        </form>
                    @else

                    <form method="POST" style="display:inline;" action="{{ route('minisite.pages.page_up', ['minisite' => $minisite, 'page' => $page]) }}">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-xs"><i class="glyphicon glyphicon-chevron-up"></i></button>
                    </form>

                    <form method="POST" style="display:inline;" action="{{ route('minisite.pages.page_down', ['minisite' => $minisite, 'page' => $page]) }}">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-xs"><i class="glyphicon glyphicon-chevron-down"></i></button>
                    </form>

                    @endif
                @endif
                </div>
            </div>
            </div>
            @endcan

        </div>
        </div>
        <div>
        <small class="text-muted">
            {{ $page->pageType->name}}
            (
            @forelse ($page->availableLanguages() as $p_lang)
            {{ $p_lang }}&nbsp;
            @empty
            {{ __('interface.minisites_page.no_language') }}
            @endforelse
            )
        </small>
        </div>
    </td>

    </tr>

    @empty

    <p>{{ __('interface.minisites_page.No_minisite_page_create_one_message') }}</p>

@endforelse

</table>

resources/views/minisite/cannot_access.blade.php
<h1>It seems like you cannot access this site.</h1>
<p>Please contact sponsorize support.</p>

resources/views/minisite/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-full">
    <div class="head-bar-nav-info">
        <h1>{{ $event->name }}</h1>
    </div>

    <div class="row">
        @include('sidebarEvent')

        <div class="col-md-10 page-content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ ucfirst(__('interface.minisites_create_page.create_title')) }}
                </div>

                <div class="panel-body">

                  @if ($errors->any())
                      <ul class="alert alert-danger">
                          @foreach ($errors->all() as $error)
                              <li>{{ $error }}</li>
                          @endforeach
                      </ul>
                  @endif

                    {!! Form::open([
                        'url' => 'events/' . $event->id . '/minisites',
                        'class' => 'form-horizontal',
                        'files' => true
                    ]) !!}

                        @include ('minisite.form')

                    {!! Form::close() !!}


                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/minisite/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-full">
    <div class="head-bar-nav-info">
        <h1>{{ $event->name }}</h1>
    </div>

    <div class="row">
        @include('sidebarEvent')

        <div class="col-md-10 page-content">
            <div class="panel panel-default">
                <div class="panel-heading">
                   {{ ucfirst(__('interface.minisites_update_page.update_title')) }}
                </div>

                <div class="panel-body">

                  {!! Form::model($minisite, [
                      'method' => 'PATCH',
                      'url' => 'events/' . $event->id . '/minisites/' . $minisite->id,
                      'class' => 'form-horizontal',
                      'files' => true
                  ]) !!}

                  @include ('minisite.form', ['submitButtonText' => ucfirst(__('interface.update'))])

                  {!! Form::close() !!}


                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/minisite/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-full">
  <div class="head-bar-nav-info">
    <h1>{{ $event->name }}</h1>
  </div>

  <div class="row">
    @include('sidebarEvent')

    <div class="col-md-10 page-content">
      <div class="panel panel-default">
        <div class="panel-heading">
          {{ ucfirst(trans_choice('models.minisite.manage_minisite', 1)) }}

          @if($minisite)
            <div class="pull-right">
              <a href="{{ $event->public_minisite ? $minisite->accessLink() : $minisite->accessLink($accessHash) }}"
                target="_blank" class="btn btn-success btn-sm btn-title-head" title="Voir le site" data-test="minisite-view">
                <i class="fa fa-eye" aria-hidden="true"></i><span class="text-link"> {{ ucfirst(trans_choice('interface.show', 1)) }}</span>
              </a>
              @can('edit', App\Minisite::class)
              <a href="{{ route('events.minisites.edit', ['event' => $event, 'minisite' => $minisite]) }}" class="btn btn-primary btn-sm btn-title-head" title="Modifier le site" data-test="minisite-edit-properties-button" >
                <i class="fa fa-pencil" aria-hidden="true"></i><span class="text-link"> {{ ucfirst(trans_choice('interface.edit_properties', 1)) }}</span>
              </a>
              @endcan
            </div>
          @endif
        </div>

        <div class="panel-body">
          @include('common._alert')

          @if($minisite)
            <div class="row">
              <div class="col-md-6">
                @include('minisite._panel_infos', ['event' => $event, 'minisite' => $minisite])
              </div>

              <div class="col-md-6">
                @include('minisite._table_pages', ['event' => $event, 'minisite' => $minisite])
              </div>
            </div>
          @else
            <p>{{ __('interface.minisites_page.No_minisite_create_one_message') }}</p>
            <a href="{{ route('events.minisites.create', ['event' => $event]) }}" class="btn btn-primary btn-sm" data-test="button-create-minisite">{{ ucfirst(__('interface.minisites_page.create_minisite')) }}</a>
          @endif
        </div>
    </div>
  </div>
</div>
</div>

@endsection

resources/views/minisite/under_construction.blade.php
<h1>This site is under construction.</h1>
<p>Please try again later.</p>